### ISSUE TITLE
Usage with Arch-based linux distros (suggestion)

### ISSUE THREAD

**Issue by Misery7100** [s-h-a-d-o-w/alfc#6]
Hello

I'm Manjaro user and find your package very cool and much better than alternatives.
I figured out how to install it for such system, so I just suggest to extend linux guide.

All next commands contain `yay` package manager, but it's easy to replace with `sudo pacman` directly.

0. Sync package databases `yay -Syu`
1. Install node: `yay -S nodejs`
2. Install headers for your kernel: `yay -S linux<XXX>-headers` where <XXX> is number of your kernel. My kernel is 5.15-32, so: `yay -S linux515-headers`
3. Install acpi_call: `yay -S acpi_call-dkms && sudo modprobe acpi_call` (don't sure need to call `modprobe`)
4. Enable `acpi_call` running on boot as in the main guide (via .conf file)
5. Download and extract linux release (e.g. v.1.0.3)
6. Open extracted directory in terminal and install alfc with `./install.sh`
7. Ignore the error `bin/sh: no command service`. If you see another error - check previous steps to cover all requirements
8. Enable service with systemctl: `sudo systemctl enable alfc`
9. Run the service `sudo systemctl start alfc`
10. Open http://localhost:5522/ and check all works fine

I don't sure it's useful, but it works :)

**Comment by s-h-a-d-o-w** [comment]
That's awesome, thanks for sharing this!
I'll think about how to best incorporate this into the readme.

To make sure that I understand your steps correctly:
At step 7, I guess the service is installed correctly but it just isn't enabled and started. But once you do enable it, it does start automatically after reboots?

Side note:
I would recommend installing acpi_call from source because the version available through `yay` might not stay compatible: https://github.com/s-h-a-d-o-w/alfc/issues/1

**Comment by s-h-a-d-o-w** [comment]
Unless of course... were you not able to install acpi_call from source like I mentioned in the guide?

**Comment by Misery7100** [comment]
> That's awesome, thanks for sharing this! I'll think about how to best incorporate this into the readme.
> 
> To make sure that I understand your steps correctly: At step 7, I guess the service is installed correctly but it just isn't enabled and started. But once you do enable it, it does start automatically after reboots?
> 
> Side note: I would recommend installing acpi_call from source because the version available through `yay` might not stay compatible: #1

- Yes, service installed correctly but it can't be enabled/started due another service manager (see https://wiki.archlinux.org/title/SysVinit and https://wiki.archlinux.org/title/Systemd);
- Yes, it's possible to install from source as well, just I thought it's  simpler to install directly from `yay`, but, of course, compatibility more important :D

**Comment by Misery7100** [comment]
By the way I've tested the utility on my 15G XC, so you can mark "It works" for linux and this model :)

**Comment by s-h-a-d-o-w** [comment]
> Yes, service installed correctly but it can't be enabled/started due another service manager (see https://wiki.archlinux.org/title/SysVinit and https://wiki.archlinux.org/title/Systemd);

But based on that wiki, Arch officially only supports systemd and that's what both my guide and the service tool I use is based on. Which means that it should just work on unmodified manjaro?

> By the way I've tested the utility on my 15G XC, so you can mark "It works" for linux and this model :)

Thanks!
I'll assume that CPU limits tweaking works as well, since that uses a standard mechanism (writing to `/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw` and `/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/constraint_1_power_limit_uw`).

**Comment by Misery7100** [comment]
The way you're trying to start/enable the service in node corresponding to sysvinit (command, syntax). It's single line I guess, so it's easy to tweak

**Comment by s-h-a-d-o-w** [comment]
You're right, my bad! Unfortunately, I currently don't have a Linux drive in my machine, so I will need to postpone this to when I can actually test it: https://github.com/s-h-a-d-o-w/alfc/issues/7

But I have just updated the Linux guide. I didn't use your concrete commands to try and keep it more general but it should be all in there.

**Comment by Misery7100** [comment]
Ok, cool! Then I close the issue :)
